-- Inserir dados de exemplo para pareceristas
INSERT INTO pareceristas (
    prefeitura_id,
    nome,
    email,
    telefone,
    cpf,
    senha_hash,
    rg,
    endereco,
    cidade,
    estado,
    cep,
    data_nascimento,
    area_atuacao,
    especialidade,
    experiencia_anos,
    formacao_academica,
    mini_curriculo,
    status,
    data_ativacao,
    created_at,
    updated_at
) VALUES 
-- Parecerista 1: Ana Costa Silva
(
    (SELECT id FROM prefeituras WHERE slug = 'jau' LIMIT 1),
    'Dr. Ana Costa Silva',
    'ana.costa@email.com',
    '(14) 99999-1234',
    '123.456.789-01',
    crypt('senha123', gen_salt('bf')),
    '12.345.678-9',
    'Rua das Artes, 123',
    'Jaú',
    'SP',
    '17200-000',
    '1985-03-15',
    'Musicologia e Produção Cultural',
    ARRAY['musica', 'cultura_popular']::Categoria_cultural[],
    15,
    'Doutora em Musicologia - UNESP, Mestre em Produção Cultural - USP',
    'Especialista em análise de projetos musicais e cultura popular com 15 anos de experiência. Atuou como curadora em diversos festivais e editais culturais.',
    'ativo',
    '2023-03-15',
    NOW(),
    NOW()
),

-- Parecerista 2: João Santos Lima
(
    (SELECT id FROM prefeituras WHERE slug = 'jau' LIMIT 1),
    'Prof. João Santos Lima',
    'joao.santos@email.com',
    '(14) 99999-5678',
    '234.567.890-12',
    crypt('senha123', gen_salt('bf')),
    '23.456.789-0',
    'Avenida do Teatro, 456',
    'Jaú',
    'SP',
    '17200-001',
    '1980-07-22',
    'Artes Cênicas e Direção Teatral',
    ARRAY['teatro', 'cinema']::Categoria_cultural[],
    12,
    'Mestre em Artes Cênicas - USP, Graduado em Direção Teatral - UNICAMP',
    'Diretor teatral e professor com 12 anos de experiência. Coordenou diversos projetos de teatro comunitário e educacional.',
    'ativo',
    '2023-05-20',
    NOW(),
    NOW()
),

-- Parecerista 3: Maria Silva Oliveira
(
    (SELECT id FROM prefeituras WHERE slug = 'jau' LIMIT 1),
    'Dra. Maria Silva Oliveira',
    'maria.silva@email.com',
    '(14) 99999-9012',
    '345.678.901-23',
    crypt('senha123', gen_salt('bf')),
    '34.567.890-1',
    'Praça das Artes, 789',
    'Jaú',
    'SP',
    '17200-002',
    '1978-11-08',
    'História da Arte e Curadoria',
    ARRAY['artes_visuais', 'literatura']::Categoria_cultural[],
    20,
    'Doutora em História da Arte - UNICAMP, Pós-doutorado em Curadoria - Sorbonne',
    'Curadora e historiadora da arte com 20 anos de experiência. Atuou em museus e galerias nacionais e internacionais.',
    'pendente',
    NULL,
    NOW(),
    NOW()
),

-- Parecerista 4: Pedro Lima Costa
(
    (SELECT id FROM prefeituras WHERE slug = 'jau' LIMIT 1),
    'Prof. Pedro Lima Costa',
    'pedro.lima@email.com',
    '(14) 99999-3456',
    '456.789.012-34',
    crypt('senha123', gen_salt('bf')),
    '45.678.901-2',
    'Rua da Dança, 321',
    'Jaú',
    'SP',
    '17200-003',
    '1990-01-14',
    'Dança Contemporânea e Coreografia',
    ARRAY['danca', 'circo']::Categoria_cultural[],
    8,
    'Especialista em Dança Contemporânea - UFBA, Graduado em Educação Física - UNESP',
    'Coreógrafo e bailarino com 8 anos de experiência. Desenvolve projetos de dança educacional e comunitária.',
    'inativo',
    '2024-01-10',
    NOW(),
    NOW()
),

-- Parecerista 5: Carlos Eduardo Santos
(
    (SELECT id FROM prefeituras WHERE slug = 'jau' LIMIT 1),
    'Prof. Carlos Eduardo Santos',
    'carlos.santos@email.com',
    '(14) 99999-6789',
    '567.890.123-45',
    crypt('senha123', gen_salt('bf')),
    '56.789.012-3',
    'Rua da Literatura, 654',
    'Jaú',
    'SP',
    '17200-004',
    '1982-09-30',
    'Literatura e Produção Editorial',
    ARRAY['literatura', 'cinema']::Categoria_cultural[],
    10,
    'Mestre em Literatura Brasileira - USP, Especialista em Produção Editorial - PUC-SP',
    'Escritor e editor com 10 anos de experiência. Coordenou diversos projetos literários e de formação de leitores.',
    'ativo',
    '2023-08-15',
    NOW(),
    NOW()
),

-- Parecerista 6: Fernanda Rodrigues
(
    (SELECT id FROM prefeituras WHERE slug = 'jau' LIMIT 1),
    'Dra. Fernanda Rodrigues',
    'fernanda.rodrigues@email.com',
    '(14) 99999-2345',
    '678.901.234-56',
    crypt('senha123', gen_salt('bf')),
    '67.890.123-4',
    'Avenida do Cinema, 987',
    'Jaú',
    'SP',
    '17200-005',
    '1987-04-12',
    'Cinema e Audiovisual',
    ARRAY['cinema', 'artes_visuais']::Categoria_cultural[],
    7,
    'Doutora em Comunicação - UNICAMP, Mestre em Cinema - ECA-USP',
    'Cineasta e pesquisadora com 7 anos de experiência. Desenvolve projetos de formação audiovisual e documentário.',
    'ativo',
    '2023-09-20',
    NOW(),
    NOW()
);

-- Atualizar estatísticas (opcional)
UPDATE prefeituras 
SET updated_at = NOW() 
WHERE slug = 'jau';
