// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymkytnhdslvkigzilbvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlta3l0bmhkc2x2a2lnemlsYnZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODE2MTAsImV4cCI6MjA3MzI1NzYxMH0.ZJpWx1g8LOxuBfO6ohJy4OKNLZAqYtw7rFPZOZjxzdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});

// Função helper para obter cliente autenticado com token customizado
export function getAuthenticatedSupabaseClient(userType: 'parecerista' | 'proponente'): SupabaseClient<Database> {
  // Obter o token baseado no tipo de usuário especificado
  const tokenKey = userType === 'parecerista' ? 'parecerista_token' : 'proponente_token';
  const token = localStorage.getItem(tokenKey);
  
  if (!token) {
    console.warn(`⚠️ Token não encontrado para ${userType}. Usando cliente não autenticado.`);
    return supabase;
  }
  
  // Debug: Verificar qual token está sendo usado
  console.log(`🔑 Usando token para ${userType}:`, token.substring(0, 50) + '...');
  try {
    const payload = JSON.parse(atob(token.split('.')[1]));
    console.log(`🔑 Payload do token ${userType}:`, {
      sub: payload.sub,
      user_type: payload.user_type,
      prefeitura_id: payload.prefeitura_id,
      email: payload.email
    });
  } catch (e) {
    console.warn('⚠️ Erro ao decodificar token:', e);
  }
  
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
    global: {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    },
  });
}