// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymkytnhdslvkigzilbvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlta3l0bmhkc2x2a2lnemlsYnZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODE2MTAsImV4cCI6MjA3MzI1NzYxMH0.ZJpWx1g8LOxuBfO6ohJy4OKNLZAqYtw7rFPZOZjxzdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});

// Função helper para obter cliente autenticado com token customizado
export function getAuthenticatedSupabaseClient(): SupabaseClient<Database> {
  // Verificar qual tipo de usuário está logado para usar o token correto
  const proponenteAuth = localStorage.getItem('proponente_auth');
  const pareceristaAuth = localStorage.getItem('parecerista_auth');
  
  let token: string | null = null;
  
  // Priorizar o token baseado no tipo de autenticação ativa
  if (pareceristaAuth) {
    // Se há autenticação de parecerista, usar o token de parecerista
    token = localStorage.getItem('parecerista_token');
  } else if (proponenteAuth) {
    // Se há autenticação de proponente, usar o token de proponente
    token = localStorage.getItem('proponente_token');
  } else {
    // Fallback: tentar qualquer token disponível (compatibilidade)
    token = localStorage.getItem('parecerista_token') || localStorage.getItem('proponente_token');
  }
  
  if (!token) {
    return supabase;
  }
  
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
    global: {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    },
  });
}